class DocPdf < Prawn::Document
  attr_accessor :doc
  
  def initialize(doc)
    super(top_margin: 50)
    @doc = doc
    heading
    doc_info
    footer
  end 

  def heading
    text "Request for Loan", size: 30, style: :bold
    stroke_horizontal_rule
    move_down 20
  end

  def doc_info
    text "#{@doc.created_at.strftime("%B %d, %Y")}", :align => :right
    move_down 10
    text "Borrower, <u> #{@doc.user.first_name} #{@doc.user.last_name} </u>, has requested a <u> #{@doc.title.downcase} </u> for the " +

    "amount of <u> #{@doc.amount}.00 </u> at the interest rate of <u> #{@doc.interest_rate} </u>%. Borrower will provide a down payment in the amount of <u>#{@doc.down_payment}.00 </u>" +

    "upon approval.", :inline_format => true
  end

  def footer
    move_down 570
    stroke_horizontal_rule
    move_down 5
    text "This document was generated by DocGenerator", size: 10, style: :bold, :align => :center
  end

  def file_name
    file_name = "users/#{@doc.user_id.to_i}/documents/#{@doc.id.to_i}.pdf"
  end

end
